from vehicle_detector_optical_flow import VehicleDetectorOpticalFlow
from vehicle_detector_background_substraction import VehicleDetectorBackgroundSubtraction

from licence_plate_detector import LicencePlateDetector
